language: ruby
rvm:
  - 2.2.0
cache: bundler
addons:
  postgresql: '9.3'
sudo: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database cakeside_test;' -U postgres
