version: '2'
services:
  web:
    build: .
    command: bundle exec foreman start web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/12
      - RAILS_LOG_TO_STDOUT=true
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
