source 'https://rubygems.org'

gem 'rails'
gem 'rake'
gem 'devise'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'carrierwave'
gem 'carrierwave_backgrounder'
gem 'rmagick'
gem 'kaminari'
gem "formtastic"
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'acts-as-taggable-on'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'jquery-fileupload-rails'
gem 'capistrano-gitflow'
gem 'dotenv-rails'
gem 'airbrake'
gem 'geocoder'
gem 'jbuilder'
gem 'pg'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'asset_sync'

group :development, :test do
  gem 'rspec-rails'
  gem 'jasmine'
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
  gem 'better_errors'
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'lol_dba'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'fakes-rspec'
  gem 'simplecov'
  gem 'ffaker'
end
group :staging do
  gem 'rack-mini-profiler'
end
group :production, :staging do
  gem 'fog'
  gem 'newrelic_rpm'
  gem 'dalli'
end
