#!/usr/bin/env bash

# example crontab entry
# 0 * * * * /home/cakeside/apps/www.cakeside.com/current/script/restart_delayed_job >> /home/cakeside/apps/www.cakeside.com/current/log/cron.log 2>&1

source /usr/local/rvm/environments/ruby-1.9.3-p194@cakeside

cd /home/cakeside/apps/www.cakeside.com/current/
script/delayed_job restart
