class Tool
  def self.all
    [
      #'ALL PURPOSE CAKE PAN',
      'Angel Food Cake Pan 6"',
      'Angel Food Cake Pan 7"',
      'Angel Food Cake Pan 8"',
      'Angel Food Cake Pan 10"',
      'Bundt/Kugelhopf 8.5"',
      'Cheesecake Pan Square 4" x 4" x 2"',
      'Cheesecake Pan Square 6" x 6" x 2"',
      'Cheesecake Pan Square 8" x 8" x 2"',
      'Cheesecake Pan Round 2" x 2"',
      'Cheesecake Pan Round 2.5" x 2"',
      'Cheesecake Pan Round 3" x 2"',
      'Cheesecake Pan Round 3" x 3"',
      'Cheesecake Pan Round 4" x 2"',
      'Cheesecake Pan Round 4" x 3"',
      'Cheesecake Pan Round 5" x 2"',
      'Cheesecake Pan Round 5" x 3"',
      'Cheesecake Pan Round 6" x 2"',
      'Cheesecake Pan Round 6" x 3"',
      'Cheesecake Pan Round 7" x 2"',
      'Cheesecake Pan Round 7" x 3"',
      'Cheesecake Pan Round 8" x 2"',
      'Cheesecake Pan Round 8" x 3"',
      'Cheesecake Pan Round 9" x 2"',
      'Cheesecake Pan Round 9" x 3"',
      'Cheesecake Pan Round 10" x 2"',
      'Cheesecake Pan Round 10" x 3"',
      'Heart Pan 6" x 2" ',
      'Heart Pan 8" x 2" ',
      'Heart Pan 9" x 2" ',
      'Heart Pan 10" x 2" ',
      'Heart Pan 10.25" x 2"',
      'Heart Pan 12" x 2" ',
      'Heart Pan 14" x 2" ',
      'Heart Pan 16" x 2" ',
      'Heart Pan 6 Cavity 2.25" x 1.25"',
      'Hexagon Pan 6" x 2"',
      'Hexagon Pan 9" x 2"',
      'Hexagon Pan 12" x 2"',
      'Hexagon Pan 15" x 2"',
      'Loaf Pan 9 1/4" x 5 1/4" x 2 3/4"',
      'Long Loaf Pan 16" x 4" x 4 1/2"',
      'Mini Angel Pan 4"',
      'Mini Angel Pan 4 1/2" x 2"',
      'Mini Fluted Pan 4"',
      'Mini Fluted Mold Pan 6 Cavity 4"cakes',
      'Mini Fluted Mold Pan 12 Cavity 4"cakes',
      'Mini Fluted Tube Pan 4"',
      'Mini Fluted Tube Pan 4 3/8" x 2"',
      'Mini Heart Pan 4"',
      'Mini Heart Pan 6 Cavity3 5/8: x 3 1/2" x 1"',
      'Mini Loaf Pan  5 3/4" x 3" x 2"',
      'Mini Ring Mold Fancy Pan',
      'Mini Round Pan 4" ',
      'Muffin Pan 12 Cup Mini Muffin',
      'Muffin Pan 24 Cup Mini Muffin',
      'Muffin Pan 6 Cup 3"',
      'Muffin Pan 12 cup 3 " ',
      'Muffin Pan 6 Cup King Size',
      'Muffin Pan 6 Cup Jumbo 4" x 2"',
      'Oval Pan 7 3/4" x 5 5/8" x 2"',
      'Oval Pan 10 3/4" x 7 5/8" x 2"',
      'Oval Pan 13" x 9 7/8" x 2"',
      'Oval Pan 16 1/2" x 12 3/8" x 2"',
      'Pannetone Pan 7" x 4"',
      'Pannetone Pan 9" x 6"',
      'Rectangular Pan 7" x 11" x 2"',
      'Rectangular Pan 7" x 11" x 3"',
      'Rectangular Pan 9" x 13" x 2"',
      'Rectangular Pan 9" x 13" x 3"',
      'Rectangular Pan 11" x 15" x 2"',
      'Rectangular Pan 11" x 15" x 3"',
      'Rectangular Pan 12" x 18" x 2"',
      'Rectangular Pan 12" x 18" x 3"',
      'Ring Mold Pan  5.25" x 2.25"',
      'Ring Mold Pan  7" x 2.25"',
      'Ring Mold Pan  8.75" x 2.25"',
      'Ring Mold Fancy Pan 10"',
      'Round Cake Pan 2" x 2" ',
      'Round Cake Pan 2" x 3" ',
      'Round Cake Pan 3" x 2" ',
      'Round Cake Pan 3" x 3" ',
      'Round Cake Pan 4" x 2" ',
      'Round Cake Pan 4" x 3" ',
      'Round Cake Pan 5" x 2" ',
      'Round Cake Pan 5" x 3" ',
      'Round Cake Pan 6" x 2" ',
      'Round Cake Pan 6" x 3" ',
      'Round Cake Pan 7" x 2" ',
      'Round Cake Pan 7" x 3" ',
      'Round Cake Pan 8" x 2" ',
      'Round Cake Pan 8" x 3" ',
      'Round Cake Pan 9" x 2" ',
      'Round Cake Pan 9" x 3" ',
      'Round Cake Pan 10" x 2"',
      'Round Cake Pan 10" x 3"',
      'Round Cake Pan 12" x 2 "',
      'Round Cake Pan 12" x 3"',
      'Round Cake Pan 14" x 2 "',
      'Round Cake Pan 14" x 3"',
      'Round Cake Pan 16" x 2"',
      'Round Cake Pan 16" x 3"',
      'Round Cake Pan 18" x 3"',
      'Sheet Cake Pan 9" x 13" x 2"',
      'Sheet Cake Pan 11" x 15" x 2"',
      'Sheet Cake Pan 12" x 18" x 2"',
      'Square Cake Pan 3" x 3" x 2"',
      'Square Cake Pan 3" x 3" x 3"',
      'Square Cake Pan 4" x 4" x 2"',
      'Square Cake Pan 4" x 4" x 3"',
      'Square Cake Pan 5" x 5" x 2"',
      'Square Cake Pan 5" x 5" x 3"',
      'Square Cake Pan 6" x 6" x 2"',
      'Square Cake Pan 6" x 6" x 3"',
      'Square Cake Pan 7" x 7" x 2"',
      'Square Cake Pan 7" x 7" x 3"',
      'Square Cake Pan 8" x 8" x 2"',
      'Square Cake Pan 8" x 8" x 3"',
      'Square Cake Pan 9" x 9" x 2"',
      'Square Cake Pan 9" x 9" x 3"',
      'Square Cake Pan 10" x 10" x 2"',
      'Square Cake Pan 10" x 10" x 3"',
      'Square Cake Pan 12" x 12" x 2"',
      'Square Cake Pan 12" x 12" x 3"',
      'Square Cake Pan 14" x 14" x 2"',
      'Square Cake Pan 14" x 14" x 3"',
      'Square Cake Pan 16" x 16" x 2"',
      'Square Cake Pan 16" x 16" x 3"',
      'Square Cake Pan 18" x 18" x 2"',
      'Square Cake Pan 18" x 18" x 3"',
      'Tart/Quche Pan 9" x 1 1/8"',
      #'WILTON SPECIALITY SHAPED PANS',
      'Wilton #1 Cake Pan',
      'Wilton 3D Bunny Pan',
      'Wilton 3D Cruiser Cake Pan',
      'Wilton 3D Egg Pan',
      'Wilton 3D Rubber Ducky Pan ',
      'Wilton Airplane Pan',
      'Wilton Antoinette Pan',
      'Wilton Baby Buggy Pan',
      'Wilton Ballerina Bear Pan',
      'Wilton Baseball Mitt Pan',
      'Wilton Belle Pan',
      'Wilton Bunny Pan',
      'Wilton Butterfly Pan',
      'Wilton Buzz Lightyear Pan',
      'Wilton Carebear Pan',
      'Wilton Cars Pixar Pan',
      'Wilton Cascade Pan',
      'Wilton Checkerboard Cake Pan',
      'Wilton Choo-Choo Train Pan',
      'Wilton Cross Pan',
      'Wilton Crown Pan',
      'Wilton Crown of Hearts Pan',
      'Wilton Cupcake Pan',
      'Wilton Dancing Daisy Pan',
      'Wilton Dinosaur Pan',
      'Wilton Doughnut Pan 6 Cavitiy',
      'Wilton Doughnut Twist Pan 6 Cavitiy',
      'Wilton Dump Truck Pan Elephant Cake Pan',
      'Wilton Elephant Pan',
      'Wilton Elmo Face Pan',
      'Wilton Enchanted Castle Pan',
      'Wilton Fanci-Fill Cake Pan',
      'Wilton Fire Truck Pan',
      'Wilton First and Ten Football Pan',
      'Wilton Football Pan',
      'Wilton Giant Cupcake Pan',
      'Wilton Gift Pan',
      'Wilton Gingerbread House Pan Mold',
      'Wilton Graduation Cap Pan',
      'Wilton Guitar Pan',
      'Wilton Half Ball Pan 3.5" x 1 3/4" ',
      'Wilton Half Ball Pan 6 1/4" x 3 1/8" ',
      'Wilton Hannah Montana Pan',
      'Wilton Helmet Pan',
      'Wilton Horseshoe Pan',
      'Wilton Jack-O-Lantern Pan',
      'Wilton Lady Bug Pan',
      'Wilton Little Mermaid Pan',
      'Wilton Mickey Mouse Head pan',
      'Wilton Mini Ball Pan',
      'Wilton Mini Bunny Pan',
      'Wilton Mini Coffin Pan',
      'Wilton Mini Cupcakes Pan',
      'Wilton Mini Decorated Heart Pan',
      'Wilton Mini Decorated Egg Pan',
      'Wilton Mini Doughnut Pan 12 Cavitiy',
      'Wilton Mini Flower Cake Pan',
      'Wilton Mini Ghost Pan',
      'Wilton Mini Gingerbread Boy Pan',
      'Wilton Mini Gingerbread Boys and Trees Pan',
      'Wilton Mini Holiday Pan',
      'Wilton Mini Jack-O-Lantern Pan',
      'Wilton Mini Pie Harvest Pan',
      'Wilton Mini Pumpkins Pan',
      'Wilton Mini Pumpkin/Ghost Pan',
      'Wilton Mini Rose Pan',
      'Wilton Mini Skulls Pan',
      'Wilton Mini Snowflakes Pan',
      'Wilton Mini Snowman',
      'Wilton Mini Snowman & Mitten Pan',
      'Wilton Mini Snowman & Stocking Pan',
      'Wilton Mini Star Pan 6 Cavity 4 3/4" x 1 1/4"',
      'Wilton Mini Tasty-Fill Pan',
      'Wilton Mini Tulip Pan',
      'Wilton Mini Wonder Mold Pan 10" x 10" x 3" (4 x 3 1/2" x 3" cakes)',
      'Wilton Monkey Pan',
      'Wilton Noah\'s Ark Pan',
      'Wilton Paisley Pan 9" x 6" x 2"',
      'Wilton Paisley Pan 12 3/4" x 9" x 2"',
      'Wilton Paisley Pan 17" x 12" x 2"',
      'Wilton Party Hat Pan',
      'Wilton Party Pony Pan ',
      'Wilton Paw Print Pan',
      'Wilton Pennant Pan',
      'Wilton Perennial Pan',
      'Wilton Petal Pan 6" x 2"',
      'Wilton Petal Pan 9" x 2"',
      'Wilton Petal Pan 12" x 2"',
      'Wilton Petal Pan 15" x 2"',
      'Wilton Petite Jack-O-Lantern Pan',
      'Wilton Pillow Pan 6 3/4" x 6 3/4" x 2"',
      'Wilton Pillow Pan 10" x 10" x 2"',
      'Wilton Pillow Pan 13 1/4" x 13 1/4" x 2"',
      'Wilton Pirate Ship Pan',
      'Wilton Princess Carriage Pan',
      'Wilton Puzzle Cakes - Animals',
      'Wilton Puzzle Cakes - Transportation',
      'Wilton Queen of Hearts Pan',
      'Wilton Rocking Horse Pan',
      'Wilton Rubber Ducky Pan',
      'Wilton Skate Pan',
      'Wilton Shamrock Pan',
      'Wilton Snowflake Pan',
      'Wilton Soccer Ball Pan',
      'Wilton Spiderman Pan',
      'Wilton Spongebob Pan',
      'Wilton Sports Ball Pan',
      'Wilton Stand-Up Cuddly Bear Pan',
      'Wilton Stand-Up House Pan',
      'Wilton Stand-Up Lamb Pan',
      'Wilton Star Pan',
      'Wilton Stars and Stripes Pan',
      'Wilton Sunflower Pan',
      'Wilton SweetHeart Pan',
      'Wilton Tasty Fill Heart Pan',
      'Wilton Teddy Bear Pan',
      'Wilton Tinkerbell Pan',
      'Wilton Topping Off Success Pan',
      'Wilton Topsy Turvy Pan',
      'Wilton Tracktor Pan',
      'Wilton Train Pan',
      'Wilton Transformers Pan',
      'Wilton Tree Pan',
      'Wilton Tulip Pan',
      'Wilton Book Pan',
      'Wilton Wall E Pan',
      'Wilton Wonder Mold Kit',
      #'NORDIC WARE SPECIALTY SHAPED PANS',
      'Nordic Ware 3D Easter Bunny Pan',
      'Nordic Ware 3D Santa Claus Pan',
      'Nordic Ware 3D Spring Lamb Pan',
      'Nordic Ware Backyard Bugs Pan',
      'Nordic Ware Beehive Pan',
      'Nordic Ware Bundt Castle Pan',
      'Nordic Ware Bundt Cathedral Pan',
      'Nordic Ware Bundt Fleur De Lis',
      'Nordic Ware Bundt Heart Pan',
      'Nordic Ware Bundt Holiday Wreath Pan',
      'Nordic Ware Bundt Poinsettia Pan',
      'Nordic Ware Bundt Sunflower Pan',
      'Nordic Ware Crème Filled Wafer Cake Pan',
      'Nordic Ware Donut Cake Pan',
      'Nordic Ware Giant Cupcake',
      'Nordic Ware Mini Garland Bundt Pan',
      'Nordic Ware Mini Multi Bundt Pan',
      'Nordic Ware Mini Pumpkin Muffin Pan',
      'Nordic Ware Pirate Ship Pan',
      'Nordic Ware Tractor Pan',
      #'PETAL CRAFTS SPECIALTY SHAPED PANS',
      'Petal Crafts 3D Medium Cupcake Pan',
      'Petal Crafts Round Mini Topsy Turvy Pan Set',
      'Petal Crafts Round Topsy Turvy 6", 8", 10", 12", 14" Pan Set',
      'Petal Crafts Square Mini Topsy Turvy',
      'Petal Crafts Quare Topsy Turvy 6", 8", 10", 12", 14" Pan Set',
    ]
  end
end
